image: node:24

stages:
  - test
  - publish

test:
  stage: test
  script:
    - npm ci
    - npm run build
    - npm test

publish:
  stage: publish
  id_tokens:
    NPM_ID_TOKEN:
      aud: "npm:registry.npmjs.org"
    SIGSTORE_ID_TOKEN:
      aud: sigstore
  script:
    - npm ci
    - npm run build --if-present
    - npm publish
  rules:
    - if: '$CI_COMMIT_TAG =~ /^v/'
